# web:
#     image: tutum/apache-php
#     ports:
#         - "80:80"
#     volumes:
#         - /var/www:/var/www
#         -  /var/www/dockerCheatSheet/docker/php.ini:/etc/php5/apache2/conf.d/30-custom.ini
#         -  /var/www/dockerCheatSheet/docker/sites:/etc/apache2/sites-enabled
#     environment: 
#         - ALLOW_OVERRIDE=true
#     links:
#         - db:db
#         - maildev:maildev


web:
    image: nginx
    ports:
        - "80:80"
    volumes: 
        - /var/www:/var/www/html
        -  /var/www/dockerCheatSheet/docker/nginx:/etc/nginx/conf.d
    links:
        - php:php

php:
    # image: php:7.1.0-fpm
    build: php
    volumes: 
        - /var/www:/var/www/html
    links: 
        - db:db
db:
    image: mysql
    volumes: 
        - /var/lib/boot2docker/mysql:/var/lib/mysql
    environment: 
        - MYSQL_ROOT_PASSWORD=root


maildev:
    image: djfarrelly/maildev
    ports:
        - "1080:80"
